version: "3"
services:
  blog:
    build: ./app
    container_name: blog
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 8000

  web:
    image: "nginx:alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/blog.conf

  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
