version: "3"
services:
  blog:
    build: ./app
    container_name: blog
    expose:
      - 8000

  web:
    image: "nginx:alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx.conf:/etc/nginx/sites-enabled/test.conf

  db:
    image: mysql
    container_name: mysql
    env_file:
      - .ENV_LOCAL
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

